### PR TITLE
feat: right-to-left support

### PR DESCRIPTION
**Pull request by boussadjra**
Issue #824

### CODE REVIEW

**Comment by bdrtsky** [comment]
Thanks for PR @boussadjra 

Too fully support RTL we will need also update styles like 

- paddingLeft to paddingStart
- marginLeft to marginStart
- paddingRight to paddingEnd
- borderLeft to borderStart
- left to insetStart
- right to insetEnd
- and so on...

Do you mind trying to add those also? Or, if it's not very urgent I could finish this in few days.

**Comment by bdrtsky** [comment]
also I think it's better to use

```css
html[dir="rtl"] {
  direction: rtl;
}
```

instead of 

```css
html[dir="rtl"] * {
  text-align: right !important;
}
```

**Comment by boussadjra** [comment]
@bdrtsky thanks, we need to update the other dependencies like `nuxt-themes/typography` and `nuxt-themes/elements`

**Comment by Tahul** [comment]
Could having a `@rtl` media query in `@nuxt-themes/tokens` help in implementing that feature?

**Comment by bdrtsky** [comment]
Back to this issue. I think having `ToggleDirection` component doesn't have practical usage, maybe put this into `app.config` instead?

**Comment by boussadjra** [comment]
If I add it to `nuxt.config` how can I switch from English to Arabic content?

**Comment by bdrtsky** [comment]
> If I add it to `nuxt.config` how can I switch from English to Arabic content?

Switching between 2 separate docs languages? Text direction should change when you switch language. Or you need to change direction even when there's only English?

**Comment by boussadjra** [comment]
You're right, I added this just to mention the ability to change direction and to checkout the right layout

**Comment by bdrtsky** [comment]
Before merge it needs those:
https://github.com/nuxt-themes/elements/pull/185
https://github.com/nuxt-themes/typography/pull/40

**Comment by bdrtsky** [comment]
There's still few issue to fix: how to handle directional icons (like, arrows), and `CodeBlock` tabs effect is broken. But in general, I would say RTL support should be pretty good. 

@boussadjra do you mind checking it when Elements & Typography will be released?

**Pull request closed without merging**
