### PR TITLE
feat(v2)!: new major version

### PR DESCRIPTION
**Pull request by bdrtsky**
Related PRs:
- https://github.com/nuxt-themes/elements/pull/189
- https://github.com/nuxt-themes/typography/pull/56
- https://github.com/nuxt-themes/elements/pull/189

This PR uses beta versions:
- `@nuxt-themes/typography@1.0.0-beta.1`
- `@nuxt-themes/tokens@2.0.0-beta.2`
- `@nuxt-themes/elements@1.0.0-beta.1`

### CODE REVIEW

**Review by Tahul — APPROVED** [review]
LGTM :) ; nice improvement in both the theme appearance and how it is structured!

Can be seen on this branch deployment, but also on Elements `v1` branch deployment, here:
https://nuxt-elements-6fp7stk2g-nuxtlabs.vercel.app/

---

### Spotted issues

CleanShot 2023-05-25 at 12 34 46

This header seem to hide a part of the text

---

CleanShot 2023-05-25 at 12 37 21

When a page has no `toc` ; the content seem to be centered but I think it should stay at the same position as a page that has it.

I'm up to discussion for this, but I feel having the content of a page moving during navigation feels inconsistent.

---

I'm not sure about the new logo and the new default color palette.

We historically used `blue` color for Docus, what was the reason for this change?

Also, maybe @R-mooon could work on a greater iteration for this logo. 😄

---

Some documentation pages content seem to be missiing, it would be worth converting them to draft (prefix `_` on the file name) or make a list of them in an issue so we can track their progress.

**Comment by bdrtsky** [comment]
Thanks for feedback @Tahul 

1. This is font issue (conflicts with gradient text CSS code, it clips some fonts). Could be workaround with increasing line height, but I wouldn't sacrifice it. This clipping appears on specific screen width, with some specific letter, in 99% other cases it looks ok.
2. This is long pending discussion. Everyone have their own preferences how it should look. I've asked multiple times to redone it.
3. This is old logo. Only thing changes is not so hilarious ghost eyes, and color in logo. Coloured logo with primary color used in absolute majority of company/project logos. As for color palette and historically `blue` Docus, well, Docus had hard history, changing the color is a way to refresh it with major version. If you dislike `orange` we could try other. Thankfully it's just a changing of `primary` color tokens.
4. Sure, converted unfinished docs to drafts.

**Comment by Tahul** [comment]
https://github.com/nuxt-themes/docus/releases/tag/v2.0.0-beta.1

Here is a list of breaking changes on the pre-release draft.

Me & @bdrtsky will work on an upgrade guide to include in that release that lists the steps for anyone to step from `v1` to `v2`.

Aside from the "landing" parts, it should be very straightforward.

**Comment by Barbapapazes** [comment]
Hello, I'm currently updating my documentation to be ready for the release, https://github.com/aneoconsulting/armonik-docs-theme/pull/44.

But I found that there is a missing margin on y for the alert.

**After**:
image

**Before**:
image

**Comment by bdrtsky** [comment]
@Barbapapazes this happens because you mix Prose components with Elements. Elements doesn't have any positioning styles, unlike Prose. I don't have a nice solution for you currently (until Pinceau fully support local css vars through props), but you can do that for now:

```
::alert{style="margin-bottom: var(--typography-verticalMargin-base)"}
alert 1
::

::alert{style="margin-bottom: var(--typography-verticalMargin-base)"}
alert 2
::
```

**Comment by Barbapapazes** [comment]
> @Barbapapazes this happens because you mix Prose components with Elements. Elements doesn't have any positioning styles, unlike Prose. I don't have a nice solution for you currently (until Pinceau fully support local css vars through props), but you can do that for now:
> 
> ```
> ::alert{style="margin-bottom: var(--typography-verticalMargin-base)"}
> alert 1
> ::
> 
> ::alert{style="margin-bottom: var(--typography-verticalMargin-base)"}
> alert 2
> ::
> ```

Thanks for this tip. Could not be the responsibility for Docus to handle this case?

**Pull request closed without merging**
