### PR TITLE
docs: update contributing in readme

### PR DESCRIPTION
**Pull request by Barbapapazes**
In order to preview change using the command `npm run dev`, we need to extend local Docus.

### CODE REVIEW

**Comment by Atinux** [comment]
Normally since we use pnpm workspace you should not have to update the docs starter.

Can you confirm @Tahul ?

**Comment by Barbapapazes** [comment]
Hoo did know about this. Will try and uodate this PR

**Comment by Barbapapazes** [comment]
You was right Atinux.

**Comment by Barbapapazes** [comment]
@Atinux I update my PR!

**Pull request merged**
