### PR TITLE
Fixed template url

### PR DESCRIPTION
**Pull request by ennioVisco**

### CODE REVIEW

**Comment by Atinux** [comment]
Actually the template is correct, see https://github.com/nuxt/starter/blob/templates/templates/themes/docus.json

**Comment by ennioVisco** [comment]
> Actually the template is correct, see https://github.com/nuxt/starter/blob/templates/templates/themes/docus.json

Ok, perhaps it's correct but it currently doesn't work.

**Comment by Atinux** [comment]
What error do you have?

**Comment by ennioVisco** [comment]
> What error do you have?

image

**Comment by Atinux** [comment]
Try with

```bash
npx nuxi@latest init -t themes/docus
```

**Comment by ennioVisco** [comment]
Ok, this seems to work. Maybe the docs should be updated accordingly?

**Comment by Atinux** [comment]
Soon everyone should have Nuxt 3.0 by default :)

**Pull request closed without merging**
