### PR TITLE
feat: add docs glow

### PR DESCRIPTION
**Pull request by bdrtsky**

### CODE REVIEW

**Comment by Atinux** [comment]
The gray for borders feels saturated, but I love the idea!

CleanShot 2022-11-16 at 17 58 28

**Comment by bdrtsky** [comment]
Noticed border issue also, think it's some rendering bug rly, because footer border renders nicely. Will investigate more on it

**Comment by Tahul** [comment]
I believe it looks better since we removed bottom <hr> on page.

Here is a screen on Safari & Chromium-based browsers:

CleanShot 2022-11-17 at 17 47 27@2x

**Comment by Atinux** [comment]
In that case I would have a background (even if dark 10%) on the previous / next link instead of a border

**Comment by bdrtsky** [comment]
Like I said, I will investigate why PrevNext borders renders differently than Footer, curious myself why this happens.

**Comment by Tahul** [comment]
We should state on this @Atinux @bdrtsky ; should I close? Should @bdrtsky update?

**Comment by bdrtsky** [comment]
Keep this open for now @Tahul 
Current glow effect also could be greatly improved.

**Pull request closed without merging**
