### PR TITLE
feat: better scrollbars

### LINKED ISSUE #642: Better scrollbar for Windows
See how we do for Volta:

- https://github.com/nuxtlabs/volta-app/blob/chore/marketing/plugins/scrollbars.client.ts
- https://github.com/nuxtlabs/volta-app/blob/chore/marketing/assets/css/scrollbars.css#L1

### PR DESCRIPTION
**Pull request by bdrtsky**
closes #642

### CODE REVIEW

**Comment by Atinux** [comment]
I would only activate it for Windows like Volta is doing:
- https://github.com/nuxtlabs/volta-app/blob/dev/assets/css/scrollbars.css
- https://github.com/nuxtlabs/volta-app/blob/dev/plugins/scrollbars.client.ts

**Comment by Tahul** [comment]
> I would only activate it for Windows like Volta is doing:
> 
> * [nuxtlabs/volta-app@`dev`/assets/css/scrollbars.css](https://github.com/nuxtlabs/volta-app/blob/dev/assets/css/scrollbars.css?rgh-link-date=2022-11-17T17%3A15%3A21Z)
> * [nuxtlabs/volta-app@`dev`/plugins/scrollbars.client.ts](https://github.com/nuxtlabs/volta-app/blob/dev/plugins/scrollbars.client.ts?rgh-link-date=2022-11-17T17%3A15%3A21Z)

😍, that's perfect, wdyt @bdrtsky ?

**Comment by bdrtsky** [comment]
Ok, but I have customized Volta scrollbar on Mac as well 😅

**Comment by Atinux** [comment]
> Ok, but I have customized Volta scrollbar on Mac as well 😅

I don't, how that's possible? Maybe the client plugin not detecting well your browser?

Does it match in your console `navigator && navigator.userAgent && navigator.userAgent.match(/Win[a-z0-9]*;/)` ?

**Comment by bdrtsky** [comment]
MacOS, Brave browser 🤷‍♂️

Screenshot 2022-11-18 at 17 07 30
Screenshot 2022-11-18 at 17 06 54
Screenshot 2022-11-18 at 17 06 03

**Comment by Atinux** [comment]
I see, cc @benjamincanac to update the regexp on Volta too

**Comment by benjamincanac** [comment]
This is really weird indeed 🤯

**Pull request merged**
