### PR TITLE
feat: try new full width fluid Container layout

### PR DESCRIPTION
**Pull request by bdrtsky**
To try this branch you need to use latest Elements commits (most likely locally using `.docs/.env` file with `THEME_DEV_ELEMENTS_PATH={pwd to Elements repo}`, until new Elements released) @Atinux @Tahul

### CODE REVIEW

**Comment by bdrtsky** [comment]
I've updated deps, so there should be any bugs to preview it now @Atinux

**Comment by Atinux** [comment]
It is looking great. But this becomes the new default?

**Review by Atinux — APPROVED** [review]

**Comment by bdrtsky** [comment]
@Atinux if you like it, I will test it more (including bigger 4k screens). I guess it could be new default, but I can support both layouts, maybe add a setting into `app.config`?

**Comment by Atinux** [comment]
What about this to activate it?

```ts
export default defineAppConfig({
  docus: {
    layout: 'fluid'
  }
})
```

**Comment by bdrtsky** [comment]
yes, exactly, could be `fluid | fixed`. I will update PR to support both.

**Pull request merged**
