### PR TITLE
fix: (partial) ERR_UNSUPPORTED_ESM_URL_SCHEME

### PR DESCRIPTION
**Pull request by Rekryt**
This is partial fix for windows problem #684

### CODE REVIEW

**Comment by grbd** [comment]
I tried running a comparison between the original and the new using `yarn build` and `yarn dev`
but didn't see any difference after the patch unfortunatley
image
image

**Comment by Rekryt** [comment]
> I tried running a comparison between the original and the new using

this is a partial fix, instead of 24 broken imports in the folder ".nuxt\prerender\" there are only 10 broken imports
image


trying to find the problem

**Comment by grbd** [comment]
Ok I think you're building against a different project with more files in so that makes more sense.
(I'm just trying to build the docs inside the docus project)

**Comment by Rekryt** [comment]
problem somewhere else

**Pull request closed without merging**
